/*
 * ps3gl_spu.c -- PPE management of the SPU vertex interleave thread.
 *
 * The SPU output goes to s_staging[] in XDR (normal host memory, DMA-accessible).
 * After ps3gl_spu_wait() the PPE copies s_staging → RSX ring buffer with memcpy.
 * The SPU never writes to RSX VRAM directly — that would fault.
 */

#include <stdio.h>
#include <string.h>
#include <malloc.h>

#include <ppu-types.h>
#include <sys/spu.h>
#include <sys/event_queue.h>
#include <lv2/spu.h>

#include "ps3gl_spu.h"

extern void ps3_log(const char *msg);

/* Embedded SPU ELF (generated by bin2s from spu_vtx.elf).
 * bin2s derives symbol names from the filename:
 *   spu_vtx_elf[]     — byte array of the ELF
 *   spu_vtx_elf_size  — uint32 length */
extern const uint8_t  spu_vtx_elf[];
extern const uint32_t spu_vtx_elf_size;

/* SPU thread handles */
static sys_spu_group_t   s_group     = 0;
static sys_spu_thread_t  s_thread    = 0;
static sys_event_queue_t s_evq       = 0;
static int               s_available = 0;

/* Job descriptor in XDR — 128-byte aligned so SPU DMA can fetch it. */
static spu_vtx_job_t s_job __attribute__((aligned(128)));

/*
 * XDR staging buffer — SPU DMA-puts interleaved vertices here.
 * 1000 vertices × 36 bytes = 36000 bytes; round to 36096 (128-byte aligned).
 * PPE then copies this to the RSX ring buffer after the SPU signals done.
 */
#define STAGING_SIZE 36096
static uint8_t s_staging[STAGING_SIZE] __attribute__((aligned(128)));

/* SPU event port for outbound mailbox → PPE event queue */
#define EVT_PORT 1

int ps3gl_spu_init(void)
{
    s_available = 0;

    s32 ret = sysSpuInitialize(1, 0);
    if (ret != 0 && ret != (s32)0x80010003 /* EEXIST */) {
        char buf[96];
        snprintf(buf, sizeof(buf), "ps3gl_spu: sysSpuInitialize: 0x%08x", (unsigned)ret);
        ps3_log(buf);
        return 0;
    }

    sysSpuImage image;
    ret = sysSpuImageImport(&image, spu_vtx_elf, 0);
    if (ret != 0) {
        char buf[96];
        snprintf(buf, sizeof(buf), "ps3gl_spu: sysSpuImageImport: 0x%08x", (unsigned)ret);
        ps3_log(buf);
        return 0;
    }

    /* Event queue: SPU outbound mailbox → PPE */
    sys_event_queue_attr_t evq_attr;
    evq_attr.attr_protocol = SYS_EVENT_QUEUE_FIFO;
    evq_attr.type          = SYS_EVENT_QUEUE_PPU;
    memset(evq_attr.name, 0, sizeof(evq_attr.name));
    evq_attr.name[0] = 'v'; evq_attr.name[1] = 't'; evq_attr.name[2] = 'x';

    ret = sysEventQueueCreate(&s_evq, &evq_attr, SYS_EVENT_QUEUE_KEY_LOCAL, 1);
    if (ret != 0) {
        char buf[96];
        snprintf(buf, sizeof(buf), "ps3gl_spu: sysEventQueueCreate: 0x%08x", (unsigned)ret);
        ps3_log(buf);
        sysSpuImageClose(&image);
        return 0;
    }

    sysSpuThreadGroupAttribute grp_attr;
    sysSpuThreadGroupAttributeInitialize(grp_attr);
    sysSpuThreadGroupAttributeName(grp_attr, "vtx_spu");

    ret = sysSpuThreadGroupCreate(&s_group, 1, 100, &grp_attr);
    if (ret != 0) {
        char buf[96];
        snprintf(buf, sizeof(buf), "ps3gl_spu: ThreadGroupCreate: 0x%08x", (unsigned)ret);
        ps3_log(buf);
        sysEventQueueDestroy(s_evq, 0);
        sysSpuImageClose(&image);
        return 0;
    }

    sysSpuThreadAttribute thr_attr;
    sysSpuThreadAttributeInitialize(thr_attr);
    sysSpuThreadAttributeName(thr_attr, "vtx_spu_t");

    sysSpuThreadArgument args;
    sysSpuThreadArgumentInitialize(args);

    ret = sysSpuThreadInitialize(&s_thread, s_group, 0, &image, &thr_attr, &args);
    if (ret != 0) {
        char buf[96];
        snprintf(buf, sizeof(buf), "ps3gl_spu: ThreadInitialize: 0x%08x", (unsigned)ret);
        ps3_log(buf);
        sysSpuThreadGroupDestroy(s_group);
        sysEventQueueDestroy(s_evq, 0);
        sysSpuImageClose(&image);
        return 0;
    }

    /* Connect SPU outbound mailbox event to our PPE event queue */
    ret = sysSpuThreadConnectEvent(s_thread, s_evq, SPU_THREAD_EVENT_USER, EVT_PORT);
    if (ret != 0) {
        char buf[96];
        snprintf(buf, sizeof(buf), "ps3gl_spu: ConnectEvent: 0x%08x", (unsigned)ret);
        ps3_log(buf);
        sysSpuThreadGroupDestroy(s_group);
        sysEventQueueDestroy(s_evq, 0);
        sysSpuImageClose(&image);
        return 0;
    }

    ret = sysSpuThreadGroupStart(s_group);
    if (ret != 0) {
        char buf[96];
        snprintf(buf, sizeof(buf), "ps3gl_spu: ThreadGroupStart: 0x%08x", (unsigned)ret);
        ps3_log(buf);
        sysSpuThreadDisconnectEvent(s_thread, SPU_THREAD_EVENT_USER, EVT_PORT);
        sysSpuThreadGroupDestroy(s_group);
        sysEventQueueDestroy(s_evq, 0);
        sysSpuImageClose(&image);
        return 0;
    }

    sysSpuImageClose(&image);
    s_available = 1;
    ps3_log("ps3gl_spu: vertex SPU thread started");
    return 1;
}

void ps3gl_spu_shutdown(void)
{
    if (!s_available) return;
    s_available = 0;

    sysSpuThreadWriteMb(s_thread, SPU_VTX_CMD_QUIT);

    u32 cause, status;
    sysSpuThreadGroupJoin(s_group, &cause, &status);

    sysSpuThreadDisconnectEvent(s_thread, SPU_THREAD_EVENT_USER, EVT_PORT);
    sysSpuThreadGroupDestroy(s_group);
    sysEventQueueDestroy(s_evq, 0);

    ps3_log("ps3gl_spu: vertex SPU thread stopped");
}

void ps3gl_spu_dispatch(const spu_vtx_job_t *job)
{
    memcpy(&s_job, job, sizeof(s_job));

    uint64_t ea = (uint64_t)(uintptr_t)&s_job;

    /* Log first dispatch so we can confirm the SPU receives it */
    static int s_first = 1;
    if (s_first) {
        char buf[96];
        snprintf(buf, sizeof(buf), "ps3gl_spu: first dispatch ea=0x%08x%08x n=%u",
                 (u32)(ea >> 32), (u32)(ea & 0xFFFFFFFFu), (unsigned)job->num_verts);
        ps3_log(buf);
        s_first = 0;
    }

    sysSpuThreadWriteMb(s_thread, SPU_VTX_CMD_JOB);
    sysSpuThreadWriteMb(s_thread, (u32)(ea >> 32));
    sysSpuThreadWriteMb(s_thread, (u32)(ea & 0xFFFFFFFFu));
}

void ps3gl_spu_wait(void)
{
    sys_event_t ev;
    /* 500 ms timeout — if SPU doesn't respond, disable it and fall back to scalar */
    s32 ret = sysEventQueueReceive(s_evq, &ev, 500 * 1000);
    if (ret != 0) {
        ps3_log("ps3gl_spu: timeout waiting for SPU — disabling SPU path");
        s_available = 0;
    }
}

void *ps3gl_spu_staging(void)
{
    return s_staging;
}

int ps3gl_spu_available(void)
{
    return s_available;
}
