/* qgl_ps3.c -- Defines qgl* globals and wires them to ps3gl. */

#include <stdio.h>
#include <string.h>

#include "qcommon/q_shared.h"
#include "renderercommon/tr_types.h"
#include "renderercommon/qgl.h"

#include "../gl/ps3gl.h"

extern void ps3_log(const char *msg);

/* qgl* global function pointer variables (replaces sdl_glimp.c definitions). */
#define GLE(ret, name, ...) name##proc * qgl##name = NULL;
QGL_1_1_PROCS;
QGL_1_1_FIXED_FUNCTION_PROCS;
QGL_DESKTOP_1_1_PROCS;
QGL_DESKTOP_1_1_FIXED_FUNCTION_PROCS;
QGL_ES_1_1_PROCS;
QGL_ES_1_1_FIXED_FUNCTION_PROCS;
QGL_1_3_PROCS;
QGL_1_5_PROCS;
QGL_2_0_PROCS;
QGL_3_0_PROCS;
QGL_ARB_occlusion_query_PROCS;
QGL_ARB_framebuffer_object_PROCS;
QGL_ARB_vertex_array_object_PROCS;
QGL_EXT_direct_state_access_PROCS;
#undef GLE

/* Extension globals -- declared in qgl.h but not generated by GLE macros. */
void (APIENTRYP qglActiveTextureARB) (GLenum texture);
void (APIENTRYP qglClientActiveTextureARB) (GLenum texture);
void (APIENTRYP qglMultiTexCoord2fARB) (GLenum target, GLfloat s, GLfloat t);

void (APIENTRYP qglLockArraysEXT) (GLint first, GLsizei count);
void (APIENTRYP qglUnlockArraysEXT) (void);

/* QGL_Init */
void QGL_Init(void)
{
    ps3_log("QGL_Init: wiring GL function pointers to ps3gl");

    /* Texture operations */
    qglBindTexture      = (BindTextureproc *)ps3gl_BindTexture;
    qglGenTextures      = (GenTexturesproc *)ps3gl_GenTextures;
    qglDeleteTextures   = (DeleteTexturesproc *)ps3gl_DeleteTextures;
    qglTexImage2D       = (TexImage2Dproc *)ps3gl_TexImage2D;
    qglTexSubImage2D    = (TexSubImage2Dproc *)ps3gl_TexSubImage2D;
    qglTexParameterf    = (TexParameterfproc *)ps3gl_TexParameterf;
    qglTexParameteri    = (TexParameteriproc *)ps3gl_TexParameteri;
    qglTexEnvf          = (TexEnvfproc *)ps3gl_TexEnvf;

    /* State management */
    qglEnable           = (Enableproc *)ps3gl_Enable;
    qglDisable          = (Disableproc *)ps3gl_Disable;
    qglBlendFunc        = (BlendFuncproc *)ps3gl_BlendFunc;
    qglAlphaFunc        = (AlphaFuncproc *)ps3gl_AlphaFunc;
    qglDepthFunc        = (DepthFuncproc *)ps3gl_DepthFunc;
    qglDepthMask        = (DepthMaskproc *)ps3gl_DepthMask;
    qglColorMask        = (ColorMaskproc *)ps3gl_ColorMask;
    qglCullFace         = (CullFaceproc *)ps3gl_CullFace;
    qglScissor          = (Scissorproc *)ps3gl_Scissor;
    qglViewport         = (Viewportproc *)ps3gl_Viewport;
    qglShadeModel       = (ShadeModelproc *)ps3gl_ShadeModel;
    qglPolygonOffset    = (PolygonOffsetproc *)ps3gl_PolygonOffset;
    qglLineWidth        = (LineWidthproc *)ps3gl_LineWidth;

    /* Clear */
    qglClear            = (Clearproc *)ps3gl_Clear;
    qglClearColor       = (ClearColorproc *)ps3gl_ClearColor;
    qglClearDepth       = (ClearDepthproc *)ps3gl_ClearDepth;
    qglClearStencil     = (ClearStencilproc *)ps3gl_ClearStencil;

    /* Matrix operations */
    qglMatrixMode       = (MatrixModeproc *)ps3gl_MatrixMode;
    qglLoadIdentity     = (LoadIdentityproc *)ps3gl_LoadIdentity;
    qglLoadMatrixf      = (LoadMatrixfproc *)ps3gl_LoadMatrixf;
    qglPushMatrix       = (PushMatrixproc *)ps3gl_PushMatrix;
    qglPopMatrix        = (PopMatrixproc *)ps3gl_PopMatrix;
    qglOrtho            = (Orthoproc *)ps3gl_Ortho;
    qglFrustum          = (Frustumproc *)ps3gl_Frustum;
    qglTranslatef       = (Translatefproc *)ps3gl_Translatef;

    /* Drawing -- immediate mode */
    qglBegin            = (Beginproc *)ps3gl_Begin;
    qglEnd              = (Endproc *)ps3gl_End;
    qglVertex2f         = (Vertex2fproc *)ps3gl_Vertex2f;
    qglVertex3f         = (Vertex3fproc *)ps3gl_Vertex3f;
    qglVertex3fv        = (Vertex3fvproc *)ps3gl_Vertex3fv;
    qglTexCoord2f       = (TexCoord2fproc *)ps3gl_TexCoord2f;
    qglTexCoord2fv      = (TexCoord2fvproc *)ps3gl_TexCoord2fv;
    qglColor3f          = (Color3fproc *)ps3gl_Color3f;
    qglColor4f          = (Color4fproc *)ps3gl_Color4f;
    qglColor4ubv        = (Color4ubvproc *)ps3gl_Color4ubv;
    qglArrayElement     = (ArrayElementproc *)ps3gl_ArrayElement;

    /* Vertex arrays */
    qglVertexPointer    = (VertexPointerproc *)ps3gl_VertexPointer;
    qglTexCoordPointer  = (TexCoordPointerproc *)ps3gl_TexCoordPointer;
    qglColorPointer     = (ColorPointerproc *)ps3gl_ColorPointer;
    qglEnableClientState  = (EnableClientStateproc *)ps3gl_EnableClientState;
    qglDisableClientState = (DisableClientStateproc *)ps3gl_DisableClientState;
    qglDrawArrays       = (DrawArraysproc *)ps3gl_DrawArrays;
    qglDrawElements     = (DrawElementsproc *)ps3gl_DrawElements;

    /* Stencil */
    qglStencilFunc      = (StencilFuncproc *)ps3gl_StencilFunc;
    qglStencilMask      = (StencilMaskproc *)ps3gl_StencilMask;
    qglStencilOp        = (StencilOpproc *)ps3gl_StencilOp;

    /* Readback */
    qglReadPixels       = (ReadPixelsproc *)ps3gl_ReadPixels;

    /* Query */
    qglGetIntegerv      = (GetIntegervproc *)ps3gl_GetIntegerv;
    qglGetBooleanv      = (GetBooleanvproc *)ps3gl_GetBooleanv;
    qglGetString        = (GetStringproc *)ps3gl_GetString;
    qglGetError         = (GetErrorproc *)ps3gl_GetError;

    /* Multitexture (GL_ARB / GL 1.3) */
    qglActiveTextureARB       = (void (APIENTRYP)(GLenum))ps3gl_ActiveTextureARB;
    qglClientActiveTextureARB = (void (APIENTRYP)(GLenum))ps3gl_ClientActiveTextureARB;
    qglMultiTexCoord2fARB     = (void (APIENTRYP)(GLenum, GLfloat, GLfloat))ps3gl_MultiTexCoord2fARB;

    /* GL 1.3 ActiveTexture -- also wire the modern name */
    qglActiveTexture    = (ActiveTextureproc *)ps3gl_ActiveTextureARB;

    /* Lock arrays */
    qglLockArraysEXT    = (void (APIENTRYP)(GLint, GLsizei))ps3gl_LockArraysEXT;
    qglUnlockArraysEXT  = (void (APIENTRYP)(void))ps3gl_UnlockArraysEXT;

    /* Desktop GL 1.1 */
    qglDepthRange       = (DepthRangeproc *)ps3gl_DepthRange;
    qglDrawBuffer       = (DrawBufferproc *)ps3gl_DrawBuffer;
    qglPolygonMode      = (PolygonModeproc *)ps3gl_PolygonMode;
    qglCopyTexSubImage2D = (CopyTexSubImage2Dproc *)ps3gl_CopyTexSubImage2D;
    qglClipPlane        = (ClipPlaneproc *)ps3gl_ClipPlane;

    /* Misc */
    qglFinish           = (Finishproc *)ps3gl_Finish;
    qglFlush            = (Flushproc *)ps3gl_Flush;

    /* GL 1.5+ / 2.0+ / 3.0+ pointers stay NULL -- not used by renderergl1 */

    ps3_log("QGL_Init: done (ps3gl layer active)");
}
