// ==========================================================
// GENERATED by gen_flavors.py from flavors.yaml — DO NOT EDIT.
// Add/change flavors in flavors.yaml and regenerate instead.
// ==========================================================

#ifndef __FLAVOR_DEFS_H
#define __FLAVOR_DEFS_H

#if defined(STANDALONETA)
  #define STANDALONE
  #define PRODUCT_NAME              "Team Arena"
  #define BASEGAME                  "baseq3"
  #define CLIENT_WINDOW_TITLE       "Quake III: Team Arena"
  #define CLIENT_WINDOW_MIN_TITLE   "teamarena"
  #define HOMEPATH_NAME_UNIX_LEGACY ".q3a"
  #define HOMEPATH_NAME             "Quake3"
  #define GAMENAME_FOR_MASTER       "Quake3Arena"
  #define CINEMATICS_LOGO           "idlogo.RoQ"
  #define CINEMATICS_INTRO          "intro.RoQ"
  #define CONFIG_PREFIX             "q3config"
  #define LEGACY_PROTOCOL
#elif defined(STANDALONEOA)
  #define PRODUCT_NAME              "OpenArena"
  #define BASEGAME                  "baseoa"
  #define CLIENT_WINDOW_TITLE       "OpenArena"
  #define CLIENT_WINDOW_MIN_TITLE   "oa"
  #define HOMEPATH_NAME_UNIX_LEGACY ".openarena"
  #define HOMEPATH_NAME             "OpenArena"
  #define GAMENAME_FOR_MASTER       "Quake3Arena"
  #define CINEMATICS_LOGO           "idlogo.roq"
  #define CINEMATICS_INTRO          "intro.roq"
  #define CONFIG_PREFIX             "oaconfig"
  #define LEGACY_PROTOCOL
#elif defined(ELITEFORCE)
  #define PRODUCT_NAME              "ioST:V HM"
  #define BASEGAME                  "baseEF"
  #define CLIENT_WINDOW_TITLE       "iostvoyHM"
  #define CLIENT_WINDOW_MIN_TITLE   "iostvoyHM"
  #define HOMEPATH_NAME_UNIX_LEGACY ".stvef"
  #define HOMEPATH_NAME             "STVEF"
  #define GAMENAME_FOR_MASTER       "EliteForce"
  #define CONFIG_PREFIX             "efconfig"
  #define LEGACY_PROTOCOL
#elif defined(STANDALONEQ3F)
  #define STANDALONE
  #define PRODUCT_NAME              "Quake 3 Fortress"
  #define BASEGAME                  "baseq3"
  #define CLIENT_WINDOW_TITLE       "Quake III: Fortress"
  #define CLIENT_WINDOW_MIN_TITLE   "q3fortress"
  #define HOMEPATH_NAME_UNIX_LEGACY ".q3a"
  #define HOMEPATH_NAME             "Quake3"
  #define GAMENAME_FOR_MASTER       "Quake3Arena"
  #define CINEMATICS_LOGO           "idlogo.RoQ"
  #define CINEMATICS_INTRO          "intro.RoQ"
  #define CONFIG_PREFIX             "q3config"
  #define LEGACY_PROTOCOL
#else
  #define PRODUCT_NAME              "ioq3"
  #define BASEGAME                  "baseq3"
  #define CLIENT_WINDOW_TITLE       "ioquake3"
  #define CLIENT_WINDOW_MIN_TITLE   "ioq3"
  #define HOMEPATH_NAME_UNIX_LEGACY ".q3a"
  #define HOMEPATH_NAME             "Quake3"
  #define GAMENAME_FOR_MASTER       "Quake3Arena"
  #define CINEMATICS_LOGO           "idlogo.RoQ"
  #define CINEMATICS_INTRO          "intro.RoQ"
  #define PROTOCOL_HANDLER          "quake3"
  #define CONFIG_PREFIX             "q3config"
  #define LEGACY_PROTOCOL
#endif

#endif // __FLAVOR_DEFS_H
